name: docs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: sudo apt install doxygen &&
             sudo python3 -m pip install sphinx &&
             sudo python3 -m pip install breathe &&
             sudo python3 -m pip install sphinx-rtd-theme
#             sudo apt install python3-sphinx &&
#             sudo apt install python3-breathe &&
#             sudo apt install python3-sphinx-rtd-theme
      - name: configure
        run: mkdir build && cd build &&
          cmake
          -DBENCODE_BUILD_TESTS=OFF
          -DBENCODE_BUILD_DOCS=ON
          -DBENCODE_BUILD_BENCHMARKS=OFF ..
      - name: build
        run: cmake --build build
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages  # default: gh-pages
          publish_dir: build/docs/sphinx