name: Tests (windows)

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  tests-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}