name: Tests (windows)

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  tests-windows-mingw:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-toolchain
      - uses: actions/checkout@v2
      - name: Configure
        run: |
            mkdir build;
            cmake -G "MinGW Makefiles" -B build -S . \
                   -DCMAKE_BUILD_TYPE=Debug \
                   -DBENCODE_BUILD_TESTS=ON \
                   -DBENCODE_ENABLE_COVERAGE=ON \
                   -DBENCODE_BUILD_DOCS=OFF \
                   -DBENCODE_BUILD_BENCHMARKS=OFF ..
      - name: Build tests
        run: cmake --build build
      - name: Run tests
        run: cd build && ctest
