name: Tests (windows)

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  tests-windows:
    runs-on: windows-latest
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            git
            base-devel
      - uses: actions/checkout@v2
      - name: Configure
        run: |
            mkdir build && cd build;
            cmake -DCMAKE_BUILD_TYPE=Debug \
                   -DBENCODE_BUILD_TESTS=ON \
                   -DBENCODE_ENABLE_COVERAGE=ON \
                   -DBENCODE_BUILD_DOCS=OFF \
                   -DBENCODE_BUILD_BENCHMARKS=OFF ..
      - name: Build tests
        run: cmake --build build
      - name: Run tests
        run: cd build && ctest