name: Tests (linux)

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Configure
      run: mkdir build && cd build &&
           cmake -DCMAKE_CXX_COMPILER=g++-10
                 -DCMAKE_BUILD_TYPE=Debug
                 -DBENCODE_BUILD_TESTS=ON
                 -DBENCODE_ENABLE_COVERAGE=ON
                 -DBENCODE_BUILD_DOCS=OFF
                 -DBENCODE_BUILD_BENCHMARKS=OFF ..
    - name: Build
      run: cmake --build build
    - name: Run tests
      run: cd build && ctest
    - name: Generate and upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }} -x gcov-10